//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperHero
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattleLog
    {
        public int Id { get; set; }
        public int UserHeroId { get; set; }
        public int OpponentHeroId { get; set; }
        public Nullable<int> WinnerHeroId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
